config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tarefas.urls')),
    path('users/', include('users.urls')),
]

tarefas/urls.py
from django.urls import path

from . import views


app_name = 'tarefas'

urlpatterns = [
    path('',views.home_page_view, name='home'),
    path('nova/', views.nova_tarefa_view, name='nova'),
    path('edita/<int:tarefa_id>', views.edita_tarefa_view, name='edita'),
    path('apaga/<int:tarefa_id>', views.apaga_tarefa_view, name='apaga'),
]

users/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

tarefas/models.py
from django.db import models

# Create your models here.


class Tarefa(models.Model):
    titulo = models.CharField(max_length=200)
    prioridade = models.IntegerField(default=1)
    concluido = models.BooleanField(default=False)
    criado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo[:50]

users/models.py
from django.db import models

# Create your models here.

tarefas/forms.py
from django import forms
from django.forms import ModelForm
from .models import Tarefa


class TarefaForm(ModelForm):
    class Meta:
        model = Tarefa
        fields = '__all__'
    # inserção de classes CSS para formatação de cada campo do formulário
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'descrição da tarefa...'}),
            'prioridade': forms.NumberInput(attrs={'class': 'form-control', 'max': 3, 'min': 1}),
        }


    # texto a exibir junto à janela de inserção
        labels = {
            'titulo': 'Título',
            'concluido': 'Concluída',
        }


    # texto auxiliar a um determinado campo do formulário
        help_texts = {
            'prioridade': 'prioridade: baixa=1, media=2, alta=3',
        }

tarefas/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


from .models import Tarefa
from .forms import TarefaForm

# imports para imprimir grafico
from matplotlib import pyplot as plt
import io
import urllib, base64
import matplotlib
matplotlib.use('Agg')


# Create your views here.

def cria_grafico():
    tarefas = Tarefa.objects.all().order_by('prioridade')

    titulos = [tarefa.titulo for tarefa in tarefas]
    prioridades = [tarefa.prioridade for tarefa in tarefas]

    plt.barh(titulos, prioridades)
    plt.ylabel("Prioridade")
    plt.autoscale()

    fig = plt.gcf()
    plt.close()

    buf = io.BytesIO()
    fig.savefig(buf, format='png')


    buf.seek(0)
    string = base64.b64encode(buf.read())
    uri = urllib.parse.quote(string)

    return uri



def home_page_view(request):

    context = {
        'tarefas': Tarefa.objects.all(),
        'data':cria_grafico()
    }
    return render(request, 'tarefas/home.html', context)


def nova_tarefa_view(request):
    form = TarefaForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('tarefas:home'))

    context = {'form': form}

    return render(request, 'tarefas/nova.html', context)


def edita_tarefa_view(request, tarefa_id):
    tarefa = Tarefa.objects.get(id=tarefa_id)
    form = TarefaForm(request.POST or None, instance=tarefa)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('tarefas:home'))

    context = {'form': form, 'tarefa_id': tarefa_id}
    return render(request, 'tarefas/edita.html', context)


def apaga_tarefa_view(request, tarefa_id):
    Tarefa.objects.get(id=tarefa_id).delete()
    return HttpResponseRedirect(reverse('tarefas:home'))

users/views.py
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render

# Create your views here.


def index_view(request):
    # se o utilizador n estiver autenticado, mandar para login
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))
    return render(request, 'users/user.html')


def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(
                    request,
                    username=username,
                    password=password
        )

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('users:index'))
        else:
            return render(request, 'users/login.html', {
                'message': 'Credenciais inválidas.'
            })

    return render(request, 'users/login.html')


def logout_view(request):
    logout(request)
    return render(request, 'users/login.html', {
        'message': 'Logged out'})

tarefas/templates/tarefas/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tarefas</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎯</text></svg>">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'tarefas/style.css' %}">
</head>
<body>
    <header class="jumbotron text-center">
        <h1>Tarefas</h1>
        <hr width="30%">
        <p>Aplicação para gerir o seu dia-a-dia</p>
    </header>

    <main class="container text-center">
    {% block main %}

    {% endblock %}
    </main>

    <section>
        {% block section %}
          
        {% endblock %}
    </section>
</body>
</html>

tarefas/templates/tarefas/edita.html
{% extends 'tarefas/base.html' %}

{% block main %}
<h3>Tarefa</h3>
    <form action="{% url 'tarefas:edita' tarefa_id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'tarefas:home' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
        <a href="{% url 'tarefas:apaga' tarefa_id %}" role="button" class="btn btn-danger">Apagar</a>
    </form>

{% endblock %}

tarefas/templates/tarefas/home.html
{% extends 'tarefas/base.html' %}

{% block main %}
    {% for tarefa in tarefas %}
        <p>
            <span class="info">
                ({{ tarefa.criado.day }}/{{ tarefa.criado.month }})
                {% if tarefa.prioridade == 1 %}
                    🟢
                {% elif tarefa.prioridade == 2 %}
                    🟡
                {% else %}
                     🔴
                {% endif %}
            </span>
            {% if tarefa.concluido == True %}
                <del>{{ tarefa.titulo }}</del>
            {% else %}
                {{ tarefa.titulo }}
            {% endif %}


            <a href="{% url 'tarefas:edita' tarefa.id %}" class="btn btn-warning  btn-sm" style="float: right; margin-right: 10px">
                Editar
            </a>
        </p>
   {% endfor %}
        <a href="{% url 'tarefas:nova' %}" class="btn btn-success btn-block">+ Nova Tarefa</a>
{% endblock %}


{% block section %}

<p><img src="data:image/png;base64,{{ data }}" alt=""></p>
<h3>Gráfico de prioridades das tarefas</h3>

{% endblock %}

tarefas/templates/tarefas/nova.html
{% extends 'tarefas/base.html' %}

{% block main %}
<h3>Nova tarefa</h3>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'tarefas:home' %}" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>

{% endblock %}

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User</title>
</head>
<body>
    {% block main %}

    {% endblock %}
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block main %}
    <h1>Login</h1>
    {% if message %}
        <div> {{ message }} </div>
    {% endif %}

    <form action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}

        <input type="text" name="username" placeholder="username"><br>
        <input type="password" name="password" placeholder="password"><br>
        <input type="submit" name="Login">
    </form>
{% endblock %}

users/templates/users/user.html
{% extends 'users/base.html' %}

{% block main %}
    <h1>Bemvindo, {{ request.user.first_name }}</h1>
    <ul>
        <li>Username: {{ request.user.username }}</li>
        <li>Email: {{ request.user.email }}</li>
    </ul>
    <a href="{% url 'users:logout' %}">Logout</a>
{% endblock %}